version: '3'

services:
  postgres:
    container_name: django-postgres
    image: mdillon/postgis:9.5
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  pgadmin:
    container_name: django-pgadmin
    image: thajeztah/pgadmin4
    ports:
      - '5050:5050'
  web:
    container_name: django-web
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres